text_offset = 0x3A2C0
text_size = 0xC60
text_address = 0x04001080
rom_file_path = "smashbrothers.us.z64"
output_file_path = "rsp/n_aspMain.cpp"
output_function_name = "n_aspMain"
extra_indirect_branch_targets = [0x10EC, 0x139C, 0x119C, 0x1A64, 0x11C8, 0x17EC, 0x1208, 0x127C, 0x1348, 0x1248, 0x1C84, 0x12D4, 0x12B0, 0x1384]